/*
 * POWERED BY
 * 
 * OKAN ÜLKER - 17050111024
 * EMRE KÖRÜS - 16050111041
 * MEHMET ALİ CABİOĞLU - 16050111044
 */
package Frames;
import Utils.SystemFunctions;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.WindowConstants;


public class AdminSettingsFrame extends javax.swing.JFrame {
   
    public AdminSettingsFrame() {
        initComponents();
        setTitle("OEM Accounting");
        lblBalance.setText(String.valueOf(SystemFunctions.getCompany().getBalance()));
        lblDebt.setText(String.valueOf(SystemFunctions.getCompany().getDebt()));
        lblClaim.setText(String.valueOf(SystemFunctions.getCompany().getClaim()));
        tfBalance.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfDebt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfClaim.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        
        this.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);

        addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {
            }

            @Override
            public void windowClosing(WindowEvent e) {
                SystemFunctions.changeToFrame(new MainFrame(), AdminSettingsFrame.this);
            }

            @Override
            public void windowClosed(WindowEvent e) {
                
            }

            @Override
            public void windowIconified(WindowEvent e) {
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
            }

            @Override
            public void windowActivated(WindowEvent e) {
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        lblDebt = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        lblClaim = new javax.swing.JLabel();
        tfBalance = new javax.swing.JTextField();
        tfDebt = new javax.swing.JTextField();
        tfClaim = new javax.swing.JTextField();
        chbBlance = new javax.swing.JCheckBox();
        chbDebt = new javax.swing.JCheckBox();
        chbClaim = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        bttChange = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(800, 250));
        setResizable(false);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        lblDebt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDebt.setText(" ");

        lblBalance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBalance.setText(" ");

        lblClaim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClaim.setText(" ");

        tfBalance.setText("New Balance");
        tfBalance.setEnabled(false);
        tfBalance.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfBalanceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfBalanceFocusLost(evt);
            }
        });
        tfBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBalanceActionPerformed(evt);
            }
        });

        tfDebt.setText("New Debt");
        tfDebt.setEnabled(false);
        tfDebt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfDebtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfDebtFocusLost(evt);
            }
        });
        tfDebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDebtActionPerformed(evt);
            }
        });

        tfClaim.setText("New Claim");
        tfClaim.setEnabled(false);
        tfClaim.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfClaimFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfClaimFocusLost(evt);
            }
        });
        tfClaim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfClaimActionPerformed(evt);
            }
        });

        chbBlance.setText("BALANCE");
        chbBlance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbBlanceActionPerformed(evt);
            }
        });

        chbDebt.setText("DEBT");
        chbDebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbDebtActionPerformed(evt);
            }
        });

        chbClaim.setText("CLAIM");
        chbClaim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbClaimActionPerformed(evt);
            }
        });

        jLabel1.setText("Choose what you want change it !");

        bttChange.setText("Change");
        bttChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttChangeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chbClaim)
                                    .addComponent(chbDebt)
                                    .addComponent(chbBlance))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblDebt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblClaim, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tfClaim, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfDebt, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfBalance, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(bttChange)))
                .addGap(29, 29, 29))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbBlance)
                    .addComponent(lblBalance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbDebt)
                    .addComponent(lblDebt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbClaim)
                    .addComponent(lblClaim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(tfDebt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(tfClaim, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bttChange)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chbClaimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbClaimActionPerformed
        // TODO add your handling code here:
        if(chbClaim.isSelected())
        {
            tfClaim.setEnabled(true);
        }
        else
        {
            tfClaim.setEnabled(false);
        }
    }//GEN-LAST:event_chbClaimActionPerformed

    private void chbDebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbDebtActionPerformed
        // TODO add your handling code here:
        if(chbDebt.isSelected())
        {
            tfDebt.setEnabled(true);
        }
        else
        {
            tfDebt.setEnabled(false);
        }
    }//GEN-LAST:event_chbDebtActionPerformed

    private void chbBlanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbBlanceActionPerformed
        // TODO add your handling code here:
        if(chbBlance.isSelected())
        {
            tfBalance.setEnabled(true);
        }
        else
        {
            tfBalance.setEnabled(false);
        }
    }//GEN-LAST:event_chbBlanceActionPerformed

    private void tfBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBalanceActionPerformed
        // TODO add your handling code here:
        tfBalance.setText("");
    }//GEN-LAST:event_tfBalanceActionPerformed

    private void tfBalanceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfBalanceFocusLost
        // TODO add your handling code here:
        if (tfBalance.getText().equalsIgnoreCase("")) {

            tfBalance.setText("New Balance");
        }
    }//GEN-LAST:event_tfBalanceFocusLost

    private void tfBalanceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfBalanceFocusGained
        // TODO add your handling code here:
        tfBalance.setText("");
    }//GEN-LAST:event_tfBalanceFocusGained

    private void bttChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttChangeActionPerformed
        // TODO add your handling code here:
        if(chbBlance.isSelected())
        {
            SystemFunctions.getCompany().setBalance(Double.parseDouble(tfBalance.getText()));
        }
        if(chbClaim.isSelected())
        {
            SystemFunctions.getCompany().setClaim(Double.parseDouble(tfClaim.getText()));
        }
        if(chbDebt.isSelected())
        {
            SystemFunctions.getCompany().setDebt(Double.parseDouble(tfDebt.getText()));
        }
        
        SystemFunctions.changeToFrame(new MainFrame(), this);
    }//GEN-LAST:event_bttChangeActionPerformed

    private void tfDebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDebtActionPerformed
        // TODO add your handling code here:
        tfDebt.setText("");
    }//GEN-LAST:event_tfDebtActionPerformed

    private void tfDebtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDebtFocusGained
        // TODO add your handling code here:
        tfDebt.setText("");
    }//GEN-LAST:event_tfDebtFocusGained

    private void tfDebtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDebtFocusLost
        // TODO add your handling code here:
        if(tfDebt.getText().equalsIgnoreCase("")){
            tfDebt.setText("New Debt");
        }
    }//GEN-LAST:event_tfDebtFocusLost

    private void tfClaimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfClaimActionPerformed
        // TODO add your handling code here:
        tfClaim.setText("");
    }//GEN-LAST:event_tfClaimActionPerformed

    private void tfClaimFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfClaimFocusGained
        // TODO add your handling code here:
        tfClaim.setText("");
    }//GEN-LAST:event_tfClaimFocusGained

    private void tfClaimFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfClaimFocusLost
        // TODO add your handling code here:
        if(tfClaim.getText().equalsIgnoreCase("")){
            tfClaim.setText("New Claim");
        }
    }//GEN-LAST:event_tfClaimFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminSettingsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminSettingsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminSettingsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminSettingsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminSettingsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttChange;
    private javax.swing.JCheckBox chbBlance;
    private javax.swing.JCheckBox chbClaim;
    private javax.swing.JCheckBox chbDebt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblClaim;
    private javax.swing.JLabel lblDebt;
    private javax.swing.JTextField tfBalance;
    private javax.swing.JTextField tfClaim;
    private javax.swing.JTextField tfDebt;
    // End of variables declaration//GEN-END:variables
}
