/*
 * POWERED BY
 * 
 * OKAN ÜLKER - 17050111024
 * EMRE KÖRÜS - 16050111041
 * MEHMET ALİ CABİOĞLU - 16050111044
 */
package Frames;

import Models.FutureOperation;
import Models.InstantOperation;
import Models.Product;
import Utils.SystemFunctions;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

public class ClaimFrame extends javax.swing.JFrame {

    private FutureOperation futureOperation;
    /**
     * Creates new form ClaimFrame
     */
    public ClaimFrame() {
        initComponents();
        setTitle("OEM Accounting");
        fillComboBox(0);
        fillTheTable();
        tfBarcode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfAmount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfDeadline.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfDiscount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfVAT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfInterestRate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfPaying.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        
        this.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);

        addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {
            }

            @Override
            public void windowClosing(WindowEvent e) {
                SystemFunctions.changeToFrame(new MainFrame(), ClaimFrame.this);
            }

            @Override
            public void windowClosed(WindowEvent e) {
                
            }

            @Override
            public void windowIconified(WindowEvent e) {
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
            }

            @Override
            public void windowActivated(WindowEvent e) {
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
            }
        });
    }
    
    private void fillComboBox(int index) {
        
        cbSearch.removeAllItems();
        ArrayList<FutureOperation> futureOperations = new ArrayList<>();
        
        for (int i = 0; i < SystemFunctions.getOperationList().size(); i++) {
            
            InstantOperation opp = (InstantOperation) SystemFunctions.getOperationList().get(i);
            
            if (opp instanceof FutureOperation && opp.getOperationType().equalsIgnoreCase("Claim") && opp.getProduct().getPrice() > 0)
                futureOperations.add((FutureOperation)opp);
        }
        
        for (int i = 0; i < futureOperations.size(); i++) {
            cbSearch.addItem(String.valueOf(futureOperations.get(i).getProduct().getBarcode()));
        }
        try {
            cbSearch.setSelectedIndex(index);
        } catch (Exception e) {
            cbSearch.setSelectedIndex(-1);
        }
        
    }
    
    private void fillTheTable() {
        int index = 0;
        
        
        DefaultTableModel model = (DefaultTableModel)tClaim.getModel();
        
        //at beginning there will be no row at all.
        model.setRowCount(0);
        
        ArrayList<FutureOperation> futureOperations = new ArrayList<>();
        
        for (int i = 0; i < SystemFunctions.getOperationList().size(); i++) {
            
            InstantOperation opp = (InstantOperation) SystemFunctions.getOperationList().get(i);
            
            if (opp instanceof FutureOperation && opp.getOperationType().equalsIgnoreCase("Claim"))
                futureOperations.add((FutureOperation)opp);
        }
        
        while (futureOperations.size() > index ) {
           model.addRow(new Object[]{
               futureOperations.get(index).getDeadline(),
               futureOperations.get(index).getProduct().getName(),
               futureOperations.get(index).getProduct().getBarcode(), 
               futureOperations.get(index).getProduct().getStock(),
               futureOperations.get(index).getProduct().getPrice(), 
               futureOperations.get(index).getValueAddedTax(),
               futureOperations.get(index).getDiscount(),
               futureOperations.get(index).getInterestRate()}); 
           index++;
        }
       
       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        cbSearch = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        taClaim = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        tfBarcode = new javax.swing.JTextField();
        tfPrice = new javax.swing.JTextField();
        tfName = new javax.swing.JTextField();
        tfAmount = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        tfDeadline = new javax.swing.JTextField();
        tfDiscount = new javax.swing.JTextField();
        tfVAT = new javax.swing.JTextField();
        tfInterestRate = new javax.swing.JTextField();
        lblMessageClaim = new javax.swing.JLabel();
        tfPaying = new javax.swing.JTextField();
        btnPay = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tClaim = new javax.swing.JTable();
        lblMessagePaying = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 250));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jRadioButton1.setText("jRadioButton1");

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel1.setText("CLAIM INFORMATION");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(471, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        cbSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSearchActionPerformed(evt);
            }
        });

        taClaim.setEditable(false);
        taClaim.setColumns(20);
        taClaim.setRows(5);
        jScrollPane2.setViewportView(taClaim);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Add Claim", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(1, 1, 1))); // NOI18N

        tfBarcode.setText("Barcode");
        tfBarcode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfBarcodeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfBarcodeFocusLost(evt);
            }
        });
        tfBarcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBarcodeActionPerformed(evt);
            }
        });

        tfPrice.setText("Price");
        tfPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfPriceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfPriceFocusLost(evt);
            }
        });
        tfPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPriceActionPerformed(evt);
            }
        });

        tfName.setText("Name");
        tfName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNameFocusLost(evt);
            }
        });
        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameActionPerformed(evt);
            }
        });

        tfAmount.setText("Amount");
        tfAmount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfAmountFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfAmountFocusLost(evt);
            }
        });
        tfAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAmountActionPerformed(evt);
            }
        });

        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        tfDeadline.setText("DD/MM/YYYY");
        tfDeadline.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfDeadlineFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfDeadlineFocusLost(evt);
            }
        });
        tfDeadline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDeadlineActionPerformed(evt);
            }
        });

        tfDiscount.setText("Discount");
        tfDiscount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfDiscountFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfDiscountFocusLost(evt);
            }
        });
        tfDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDiscountActionPerformed(evt);
            }
        });

        tfVAT.setText("VAT");
        tfVAT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfVATFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfVATFocusLost(evt);
            }
        });
        tfVAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfVATActionPerformed(evt);
            }
        });

        tfInterestRate.setText("Interest Rate");
        tfInterestRate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfInterestRateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfInterestRateFocusLost(evt);
            }
        });
        tfInterestRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfInterestRateActionPerformed(evt);
            }
        });

        lblMessageClaim.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        lblMessageClaim.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfVAT, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfDeadline, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfBarcode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(tfName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfDiscount)
                            .addComponent(tfAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(tfPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(tfInterestRate))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblMessageClaim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfVAT, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfInterestRate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMessageClaim, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addContainerGap())
        );

        tfPaying.setText("Amount");
        tfPaying.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfPayingFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfPayingFocusLost(evt);
            }
        });
        tfPaying.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPayingActionPerformed(evt);
            }
        });

        btnPay.setText("PAY");
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        tClaim.setBorder(new javax.swing.border.MatteBorder(null));
        tClaim.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Deadline", "Product Name", "Barcode No", "Amount", "Price", "KDV", "Discount", "Interest Rate"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tClaim.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tClaim);

        lblMessagePaying.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        lblMessagePaying.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfPaying, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbSearch, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(lblMessagePaying, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPay, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(tfPaying))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMessagePaying, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            if (SystemFunctions.getTimeDifference(tfDeadline.getText()) > 0) {
                futureOperation = new FutureOperation("Claim", new Product(Integer.parseInt(tfBarcode.getText()), tfName.getText(), Integer.parseInt(tfAmount.getText()), Double.parseDouble(tfPrice.getText())), Double.parseDouble(tfVAT.getText()), Double.parseDouble(tfDiscount.getText()), tfDeadline.getText(), Double.parseDouble(tfInterestRate.getText()));
            
                if (SystemFunctions.isOperationAvailable(futureOperation)) {
                    SystemFunctions.addOperation(futureOperation);
                    fillComboBox(0);
                    fillTheTable();
                    lblMessageClaim.setText("The products are sold.");
                } else {
                    lblMessageClaim.setText("There is no stock");
                }
                
            }
            else{
                lblMessageClaim.setText("The process is fail");
            }
        } catch (ParseException ex) {
            lblMessageClaim.setText("Enter the date correctly!!");
        } catch (NumberFormatException e) {
            lblMessageClaim.setText("Fill the blanks correctly!!");
        } 
    }//GEN-LAST:event_btnAddActionPerformed

    private void tfBarcodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfBarcodeFocusGained
        tfBarcode.setText("");
    }//GEN-LAST:event_tfBarcodeFocusGained

    private void tfBarcodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfBarcodeFocusLost
        if (tfBarcode.getText().equalsIgnoreCase("")) {

            tfBarcode.setText("Barcode");
        }
    }//GEN-LAST:event_tfBarcodeFocusLost

    private void tfPriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPriceFocusGained
         tfPrice.setText("");
    }//GEN-LAST:event_tfPriceFocusGained

    private void tfPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPriceFocusLost
        if (tfPrice.getText().equalsIgnoreCase("")) {

            tfPrice.setText("Price");
        }
    }//GEN-LAST:event_tfPriceFocusLost

    private void tfNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNameFocusGained
         tfName.setText("");
    }//GEN-LAST:event_tfNameFocusGained

    private void tfNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNameFocusLost
        if (tfName.getText().equalsIgnoreCase("")) {

            tfName.setText("Name");
        }
    }//GEN-LAST:event_tfNameFocusLost

    private void tfAmountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfAmountFocusGained
         tfAmount.setText("");
    }//GEN-LAST:event_tfAmountFocusGained

    private void tfAmountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfAmountFocusLost
        if (tfAmount.getText().equalsIgnoreCase("")) {

            tfAmount.setText("Amount");
        }
    }//GEN-LAST:event_tfAmountFocusLost

    private void tfDeadlineFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDeadlineFocusGained
         tfDeadline.setText("");
    }//GEN-LAST:event_tfDeadlineFocusGained

    private void tfDeadlineFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDeadlineFocusLost
        if (tfDeadline.getText().equalsIgnoreCase("")) {

            tfDeadline.setText("DD/MM/YYYY");
        }
    }//GEN-LAST:event_tfDeadlineFocusLost

    private void tfBarcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBarcodeActionPerformed
         tfBarcode.setText("");
    }//GEN-LAST:event_tfBarcodeActionPerformed

    private void tfPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPriceActionPerformed
         tfPrice.setText("");
    }//GEN-LAST:event_tfPriceActionPerformed

    private void tfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameActionPerformed
         tfName.setText("");
    }//GEN-LAST:event_tfNameActionPerformed

    private void tfAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAmountActionPerformed
         tfAmount.setText("");
    }//GEN-LAST:event_tfAmountActionPerformed

    private void tfDeadlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDeadlineActionPerformed
         tfDeadline.setText("");
    }//GEN-LAST:event_tfDeadlineActionPerformed

    private void tfDiscountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDiscountFocusGained
         tfDiscount.setText("");
    }//GEN-LAST:event_tfDiscountFocusGained

    private void tfDiscountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDiscountFocusLost
       if (tfDiscount.getText().equalsIgnoreCase("")) {

            tfDiscount.setText("Discount");
        }
    }//GEN-LAST:event_tfDiscountFocusLost

    private void tfDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDiscountActionPerformed
        tfDiscount.setText("");
    }//GEN-LAST:event_tfDiscountActionPerformed

    private void tfVATFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfVATFocusGained
         tfVAT.setText("");
    }//GEN-LAST:event_tfVATFocusGained

    private void tfVATFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfVATFocusLost
        if (tfVAT.getText().equalsIgnoreCase("")) {

            tfVAT.setText("VAT");
        }
    }//GEN-LAST:event_tfVATFocusLost

    private void tfVATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfVATActionPerformed
         tfVAT.setText("");
    }//GEN-LAST:event_tfVATActionPerformed

    private void tfInterestRateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfInterestRateFocusGained
         tfInterestRate.setText("");
    }//GEN-LAST:event_tfInterestRateFocusGained

    private void tfInterestRateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfInterestRateFocusLost
        if (tfInterestRate.getText().equalsIgnoreCase("")) {

            tfInterestRate.setText("Interest Rate");
        }
    }//GEN-LAST:event_tfInterestRateFocusLost

    private void tfInterestRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfInterestRateActionPerformed
         tfInterestRate.setText("");
    }//GEN-LAST:event_tfInterestRateActionPerformed

    private void tfPayingFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPayingFocusGained
        tfPaying.setText("");
    }//GEN-LAST:event_tfPayingFocusGained

    private void tfPayingFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPayingFocusLost
        if (tfPaying.getText().equalsIgnoreCase("")) {

            tfPaying.setText("Amount");
        }
    }//GEN-LAST:event_tfPayingFocusLost

    private void tfPayingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPayingActionPerformed
        tfPaying.setText("");
    }//GEN-LAST:event_tfPayingActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        
 
        for (int i = 0; i < SystemFunctions.getOperationList().size(); i++) {
           
                if(SystemFunctions.getOperationList().get(i) instanceof FutureOperation){
                    if (    SystemFunctions.getOperationList().get(i).getOperationType().equalsIgnoreCase("Claim") &&
                            ((FutureOperation)(SystemFunctions.getOperationList().get(i))).getProduct().getBarcode() == Integer.parseInt(cbSearch.getSelectedItem().toString()) && 
                            ((FutureOperation)(SystemFunctions.getOperationList().get(i))).getProduct().getPrice() >= Double.parseDouble(tfPaying.getText())) {
                        
                       SystemFunctions.getOperationList().get(i).getProduct().setPrice(SystemFunctions.getOperationList().get(i).getProduct().getPrice() - Double.parseDouble(tfPaying.getText()));
                       SystemFunctions.saveOperationsToDatabase();
                       SystemFunctions.getCompany().setClaim(SystemFunctions.getCompany().getClaim() - Double.parseDouble(tfPaying.getText()));
                       SystemFunctions.getCompany().setBalance(SystemFunctions.getCompany().getBalance() + Double.parseDouble(tfPaying.getText()));
                       lblMessagePaying.setText("The Process is successful");
                       taClaim.setText(null);
                       fillComboBox(cbSearch.getSelectedIndex());
                       fillTheTable();
                       return;
                    }
                    else{
                       lblMessagePaying.setText("The Process is fail");

                    }
                       
                }
        }
        
        
        
        
    }//GEN-LAST:event_btnPayActionPerformed

    private void cbSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSearchActionPerformed
        // TODO add your handling code here:
        if(cbSearch.getSelectedIndex()>=0){
        for(int i =0; i<SystemFunctions.getOperationList().size();i++){    
            String result = "Claim Information\n\n";
            if(SystemFunctions.getOperationList().get(i) instanceof FutureOperation){
                 if (
                         SystemFunctions.getOperationList().get(i).getOperationType().equalsIgnoreCase("Claim") &&
                         ((FutureOperation)(SystemFunctions.getOperationList().get(i))).getProduct().getBarcode() == Integer.parseInt(cbSearch.getSelectedItem().toString())){
                        
                        result += "Deadline: " + ((FutureOperation)(SystemFunctions.getOperationList().get(i))).getDeadline() + "\n";
                        result += "Product Name: " + ((FutureOperation)(SystemFunctions.getOperationList().get(i))).getProduct().getName() + "\n";
                        result += "Barcode No:" + ((FutureOperation)(SystemFunctions.getOperationList().get(i))).getProduct().getBarcode() + "\n"; 
                        result += "Amount: " + ((FutureOperation)(SystemFunctions.getOperationList().get(i))).getProduct().getStock() + "\n";
                        result += "Price: " + ((FutureOperation)(SystemFunctions.getOperationList().get(i))).getProduct().getPrice() + "\n"; 
                        result += "VAT: " + ((FutureOperation)(SystemFunctions.getOperationList().get(i))).getValueAddedTax() + "\n";
                        result += "Discount: " + ((FutureOperation)(SystemFunctions.getOperationList().get(i))).getDiscount() + "\n";
                        result += "Interest Rate: " + ((FutureOperation)(SystemFunctions.getOperationList().get(i))).getInterestRate() + "\n";
                        taClaim.setText(result);
                 }
            }   }
        }
    }//GEN-LAST:event_cbSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClaimFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClaimFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClaimFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClaimFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClaimFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnPay;
    private javax.swing.JComboBox<String> cbSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblMessageClaim;
    private javax.swing.JLabel lblMessagePaying;
    private javax.swing.JTable tClaim;
    private javax.swing.JTextArea taClaim;
    private javax.swing.JTextField tfAmount;
    private javax.swing.JTextField tfBarcode;
    private javax.swing.JTextField tfDeadline;
    private javax.swing.JTextField tfDiscount;
    private javax.swing.JTextField tfInterestRate;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfPaying;
    private javax.swing.JTextField tfPrice;
    private javax.swing.JTextField tfVAT;
    // End of variables declaration//GEN-END:variables
}
